from fastapi import FastAPI, Header
from typing import Optional
import praw
import pandas as pd
import os
import yt_dlp
import subprocess
import asyncio
from playwright.async_api import async_playwright
import time # Import time for delays

import io
from http.cookiejar import MozillaCookieJar
from yt_dlp.cookies import YoutubeDLCookieJar

app = FastAPI()

reddit =praw.Reddit(
client_id="eooRep-EWsgQSo_jIV9t9A", #client id
client_secret="cilB13w2PkGVk9XmNowgZbjIrJTypA",#client secret
user_agent="let`s_fight")

@app.post("/top-posts")
def get_top_posts(
    x_subreddit_name: Optional[str] = Header(default="miku", alias="X-Subreddit-Name"),
    x_num_of_posts: Optional[int] = Header(default=900, alias="X-Num-Of-Posts")
):
    subreddit = reddit.subreddit(x_subreddit_name)
    top_posts_list = list(subreddit.new(limit=x_num_of_posts))
    if subreddit.over18:
        posts=[{"error":"hentai warning"},{"aurthor":"Phares"}]
    else:
        posts = [
            {
                "Title": post.title,
                "score": post.score,
                "urls": post.url,
                "number of comments": post.num_comments
            }
            for post in top_posts_list
            if not post.over_18
        ]   

    return {"count": len(posts), "posts": posts}

@app.post("/get-vid")
def download_video(url:Optional[str]=Header(alias="url")):



    log_path = "download.log"
    cookie_file = "cookies.txt"

    # Open the log file to capture yt-dlp's output
    with open(log_path, "w") as log_file:
    # Run yt-dlp in the background as a list of arguments
         process = subprocess.Popen(
        ["yt-dlp","-f ","bestvideo[ext=mp4]+bestaudio[ext=m4a]/best","--rm-cache-dir","--no-cache-dir","--cookies",cookie_file , url,"-o","vid.%(ext)s"],
        stdout=log_file,
        stderr=log_file
         

)
    

@app.post("/delete-vid")
def download_video():
    try:
        os.remove(shared-videos/video.mp4)
        return 0
    except Exception as e:
        return {"status": "error", "message": str(e)} 

    



RAW_COOKIES ="""# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	FALSE	1816546362	HSID	AlHpLdCntdMsEMhru
.youtube.com	TRUE	/	TRUE	1816546362	SSID	A9f9U8plESoPOopD_
.youtube.com	TRUE	/	FALSE	1816546362	APISID	RbKO0wuzzC2TTP2q/A6hBzTZwmQXDi4SK5
.youtube.com	TRUE	/	TRUE	1816546362	SAPISID	uF5yAOQt_1fF42pQ/AApgfd8Ngibk3k6qL
.youtube.com	TRUE	/	TRUE	1816546362	__Secure-1PAPISID	uF5yAOQt_1fF42pQ/AApgfd8Ngibk3k6qL
.youtube.com	TRUE	/	TRUE	1816546362	__Secure-3PAPISID	uF5yAOQt_1fF42pQ/AApgfd8Ngibk3k6qL
.youtube.com	TRUE	/	FALSE	1816546362	SID	g.a000_QgGrfcJwzTPqcXKR-qR6uMwuU2n87KvxvGFa2soBPk8ufsLFixwA8S8oT5h-WwerEsgWQACgYKAQkSARESFQHGX2MiV2AV0Z9X4g4wJzem2vKTZxoVAUF8yKoDuENf2DbQwXCaQkABEp6N0076
.youtube.com	TRUE	/	TRUE	1816546362	__Secure-1PSID	g.a000_QgGrfcJwzTPqcXKR-qR6uMwuU2n87KvxvGFa2soBPk8ufsLYY6uVdNA5CS57hjsFtWhoAACgYKAbwSARESFQHGX2MieisAgaiBtlz1KsxX_mJgAhoVAUF8yKr-I-Cdkn2_0ctN-Zn-kNNk0076
.youtube.com	TRUE	/	TRUE	1816546362	__Secure-3PSID	g.a000_QgGrfcJwzTPqcXKR-qR6uMwuU2n87KvxvGFa2soBPk8ufsL7VGjNm6keAyFZp9BfS-h1gACgYKAX4SARESFQHGX2MiyJx8tfSxM5WLbaSomFv8-RoVAUF8yKqQ50UH_yJCQnLj3AYi4W8G0076
.youtube.com	TRUE	/	TRUE	1816546363	LOGIN_INFO	AFmmF2swRAIgYoHwQOSQx990IG8B2VjBOr2GLSl1YsnFoUdy2TjVNL8CIH61JWKt8XLcvgprAPKzqOPmUJQHu1AMGGQT3WjJRj_3:QUQ3MjNmeVliS25yWEl2aUp4U2puSDV3UUg2UjlEV0E1MXdNeHFYaFBzZ3BhSmdpdnFnVW1sbm9TMElJZzRYRWdSY2U4dmtpREhhUkxaZ3JHemk5cG13LWE0TUM5ZE5zTFJZa2RNZmVkTlZET2NHNXc0d3U2S3RQYUx2Rl83dC1aOVprU3k2elZkTnphanB5NUtZak5MM1dCOUdsSy1jeHV3
.youtube.com	TRUE	/	FALSE	0	PREF	f4=4000000&f6=40000000&tz=UTC&f7=140&f5=30000&hl=en
.youtube.com	TRUE	/	TRUE	1813933724	efyt_experiments	modern_player=0&ultra_wide_player=0
.youtube.com	TRUE	/	TRUE	1814169515	__Secure-1PSIDTS	sidts-CjQByojQU1SsIRIYV1dJRUKFAZmyloUWprA0RRT1bXvWffeRyL6BsZPL4mVrmU34hnkM0KtpEAA
.youtube.com	TRUE	/	TRUE	1814169515	__Secure-3PSIDTS	sidts-CjQByojQU1SsIRIYV1dJRUKFAZmyloUWprA0RRT1bXvWffeRyL6BsZPL4mVrmU34hnkM0KtpEAA
.youtube.com	TRUE	/	FALSE	1814170412	SIDCC	AKEyXzW13hAUb6KnfHxYiVc6AiVWVN-ZxTBir_bxhpAhzpSYQWUpUjmqtmHIkbjt0Ol3bOdFWQ
.youtube.com	TRUE	/	TRUE	1814170412	__Secure-1PSIDCC	AKEyXzVxKpXfp909_E0NhJ0TVtgdopTnRpzPV0RS3vtrDE2gD1ZJl3QCcQdrZQ9auZUI46YDJ9Y
.youtube.com	TRUE	/	TRUE	1814170412	__Secure-3PSIDCC	AKEyXzVVIcOS_eajaNy-_ZBV-McISj37W2wIGxUHKGypfoZ0I0wX6V50SyKRnKFv1UI72NkVm9c
.youtube.com	TRUE	/	TRUE	1798186412	VISITOR_INFO1_LIVE	IS0aX43nXns
.youtube.com	TRUE	/	TRUE	1798186412	VISITOR_PRIVACY_METADATA	CgJFRxIEGgAgIg%3D%3D
.youtube.com	TRUE	/	TRUE	1798137119	__Secure-YNID	19.YT=ISWa8tkaI7a3q5jIhW8rc0vGByieuzpjjFbuLgzkJqwr17oTWRPQeZJz0FnR13bocDkjJQ90p_W4DOqRr-Yi9L9m_1nK-YEu5WORRF8eLoboEitf_XbZAFhlLXwOJiTp2mZs7jFkWWdFeXIrjPyyhnPv4XmtqdP_8zpSzKqmvhk1BKbc7L3MWVGcZfA4mPXrktotyPvg4Chh6fXwPuiOB9g0r6dH8mQFoM3i0i1NCcIFgZ5tYa62yfE95OdwqVxTIxiucOc9ZVQvh95WmX2OEuk1ZqommqGjdA9VrnDoCNkksxInxJURYukvhamiHYT6fKfOrkweTr3cHyM57oAuMQ
.youtube.com	TRUE	/	TRUE	1798137119	__Secure-ROLLOUT_TOKEN	CMzesKqO346T6AEQwLTKmNCWlQMYmOmAhoeolQM%3D
.youtube.com	TRUE	/	TRUE	0	YSC	kBLiR9JojUU
"""

@app.post("/download-video")
def download_youtube_video( url:Optional[str]=Header(alias="url")):
    try:
        ydl_opts = {
            'format': 'bestvideo+bestaudio/best',
            'outtmpl': f'/app/vid.%(ext)s',
            'quiet': True,

            # Prevent yt-dlp from caching or attempting to modify the memory stream
            'cache_dir': False,
            'no_write_playlist_metafiles': True,
        }
        cookie_jar = MozillaCookieJar()

        with io.StringIO(RAW_COOKIES.strip()) as cookie_stream:
            cookie_jar._really_load(cookie_stream, "RAW_COOKIES", ignore_discard=False, ignore_expires=False)
            
        # 3. FORCE the standard cookie jar to use the yt-dlp subclass features
        cookie_jar.__class__ = YoutubeDLCookieJar
            
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            # 4. Inject the modified cookie jar securely
            ydl.cookiejar = cookie_jar
            
            # Execute download
            info_dict = ydl.extract_info(url, download=True)
            video_title = info_dict.get('title', 'Unknown Title')
            filename = ydl.prepare_filename(info_dict)
            
        return {
            "status": "success",
            "title": video_title,
            "saved_path": filename
        }
        
    except Exception as e:
        return {"status": "error", "message": str(e)}


async def scrape_pinterest_pins(search):
    scroll=1
    
    url = f"https://www.pinterest.com/search/pins/?q={search}&rs=typed"

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        print(f"Navigating to {url}")
        await page.goto(url, wait_until='domcontentloaded')

        # Add a small delay to ensure visual rendering after network idle
        await page.wait_for_timeout(3000) # Wait for 3 seconds

        # --- Scroll down to load more content ---
        print("Scrolling down to load more content...")
        for _ in range(scroll): # Scroll 5 times (adjust as needed)
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await page.wait_for_timeout(2000) # Wait for content to load after scroll
        print("Finished scrolling.")
        # ----------------------------------------

        try:
            print("Waiting for a Pinterest pin element to be visible (max 30 seconds)...")
            pin_selector = 'div[data-test-id="non-story-pin-image"]'

            await page.wait_for_selector(pin_selector, timeout=30000)
            print("At least one pin element found. Extracting pin information.")

            pin_elements = await page.locator(pin_selector).all()
            print(f"Found {len(pin_elements)} pins on the page.")

            extracted_pins = []
            for i, pin_element in enumerate(pin_elements):
                if i >= 40: # Extract only first 40 for brevity
                    break
                pin_data = {}
                img_locator = pin_element.locator('img')
                if await img_locator.count() > 0:
                    pin_data['image_src'] = await img_locator.first.get_attribute('src')
                    pin_data['image_alt'] = await img_locator.first.get_attribute('alt')

                text_locator = pin_element.locator('div[data-test-id="pin-title"]')
                if await text_locator.count() > 0:
                    pin_data['title'] = await text_locator.first.inner_text()
                else:
                    text_content = await pin_element.text_content()
                    pin_data['description_snippet'] = text_content[:100].replace('\n', ' ') if text_content else ''

                extracted_pins.append(pin_data)
            # Move the return statement outside the loop
            return extracted_pins
        except Exception as e:
            print(f"Error during element extraction: {e}")
            print("Could not find expected dynamic elements or timed out. Check the screenshot and selectors.")

        await browser.close()
        print("Browser closed.")
        # If an error occurs or no pins are found, return an empty list
        return []


@app.post("/pin")
async def read_results(query:Optional[str]=Header(alias="query")):
    results = await scrape_pinterest_pins(query)
    return results
